wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.23
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 1
      - 3
      - 5
      2:
      - 1
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      4: 3.8.3
      5: 0.10.23
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 91
criterion:
  desc: null
  value: mean_squared_error
epochs:
  desc: null
  value: 20
h1:
  desc: null
  value: 16
h2:
  desc: null
  value: 64
h3:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.01023454695901821
method:
  desc: null
  value: random
metric:
  desc: null
  value:
    goal: minimize
    name: loss
name:
  desc: null
  value: NN-test-sweep-keras
optimizer:
  desc: null
  value: RMSprop
parameters:
  desc: null
  value:
    batch_size:
      distribution: q_log_uniform
      max: 5.545177444479562
      min: 3.4657359027997265
      q: 1
    criterion:
      values:
      - mean_squared_error
    epochs:
      values:
      - 100
      - 20
      - 30
      - 40
      - 50
      - 80
    h1:
      values:
      - 8
      - 16
      - 32
      - 64
      - 256
    h2:
      values:
      - 8
      - 16
      - 32
      - 64
      - 256
    h3:
      values:
      - 8
      - 16
      - 32
      - 64
      - 256
    learning_rate:
      distribution: uniform
      max: 0.1
      min: 0
    optimizer:
      values:
      - Adam
      - Adagrad
      - RMSprop
