wandb_version: 1

batch_size:
  value: 228
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 32
h2:
  value: 16
h3:
  value: 256
learning_rate:
  value: 0.005519434392198231
optimizer:
  value: ada
