wandb_version: 1

batch_size:
  value: 155
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 8
h2:
  value: 256
h3:
  value: 16
learning_rate:
  value: 0.05976149495741754
optimizer:
  value: rms
