wandb_version: 1

batch_size:
  value: 214
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 16
h2:
  value: 32
h3:
  value: 8
learning_rate:
  value: 0.051332763920076324
optimizer:
  value: rms
