wandb_version: 1

batch_size:
  value: 71
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 16
h2:
  value: 256
h3:
  value: 16
learning_rate:
  value: 0.04687516994484288
optimizer:
  value: adam
