wandb_version: 1

batch_size:
  value: 34
criterion:
  value: bce
epochs:
  value: 1
h1:
  value: 256
h2:
  value: 8
h3:
  value: 32
learning_rate:
  value: 0.09497183790432419
optimizer:
  value: adam
