wandb_version: 1

batch_size:
  value: 78
criterion:
  value: bce
epochs:
  value: 1
h1:
  value: 256
h2:
  value: 16
h3:
  value: 32
learning_rate:
  value: 0.0932274661142935
optimizer:
  value: adam
