wandb_version: 1

batch_size:
  value: 120
criterion:
  value: bce
epochs:
  value: 1
h1:
  value: 8
h2:
  value: 256
h3:
  value: 256
learning_rate:
  value: 0.07667091510215834
optimizer:
  value: sgd
