wandb_version: 1

batch_size:
  value: 86
criterion:
  value: mse
epochs:
  value: 1
h1:
  value: 16
h2:
  value: 256
h3:
  value: 64
learning_rate:
  value: 0.09026159586902233
optimizer:
  value: adam
