wandb_version: 1

batch_size:
  value: 45
criterion:
  value: mse
epochs:
  value: 80
h1:
  value: 8
h2:
  value: 16
h3:
  value: 64
learning_rate:
  value: 0.07511653785571848
optimizer:
  value: adam
