wandb_version: 1

batch_size:
  value: 78
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 16
h2:
  value: 16
h3:
  value: 16
learning_rate:
  value: 0.04758722633735374
optimizer:
  value: adam
