wandb_version: 1

batch_size:
  value: 62
criterion:
  value: mse
epochs:
  value: 20
h1:
  value: 8
h2:
  value: 256
h3:
  value: 64
learning_rate:
  value: 0.0774304309004139
optimizer:
  value: rms
