wandb_version: 1

batch_size:
  value: 69
criterion:
  value: mse
epochs:
  value: 20
h1:
  value: 32
h2:
  value: 16
h3:
  value: 16
learning_rate:
  value: 0.09609297665040804
optimizer:
  value: ada
