wandb_version: 1

batch_size:
  value: 148
criterion:
  value: mse
epochs:
  value: 100
h1:
  value: 256
h2:
  value: 16
h3:
  value: 256
learning_rate:
  value: 0.007207625999826495
optimizer:
  value: ada
