wandb_version: 1

batch_size:
  value: 221
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 64
h2:
  value: 16
h3:
  value: 256
learning_rate:
  value: 0.029680942378730424
optimizer:
  value: ada
