wandb_version: 1

batch_size:
  value: 90
criterion:
  value: mse
epochs:
  value: 40
h1:
  value: 64
h2:
  value: 8
h3:
  value: 16
learning_rate:
  value: 0.030338839311584778
optimizer:
  value: rms
