wandb_version: 1

batch_size:
  value: 78
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 16
h2:
  value: 64
h3:
  value: 32
learning_rate:
  value: 0.03826767144646747
optimizer:
  value: ada
