wandb_version: 1

batch_size:
  value: 39
criterion:
  value: mse
epochs:
  value: 30
h1:
  value: 64
h2:
  value: 64
h3:
  value: 64
learning_rate:
  value: 0.08541865318894626
optimizer:
  value: rms
