wandb_version: 1

batch_size:
  value: 45
criterion:
  value: mse
epochs:
  value: 100
h1:
  value: 32
h2:
  value: 16
h3:
  value: 64
learning_rate:
  value: 0.021375881072456405
optimizer:
  value: ada
