wandb_version: 1

batch_size:
  value: 100
criterion:
  value: mse
epochs:
  value: 100
h1:
  value: 8
h2:
  value: 256
h3:
  value: 64
learning_rate:
  value: 0.07787376385930571
optimizer:
  value: adam
