wandb_version: 1

batch_size:
  value: 41
criterion:
  value: mse
epochs:
  value: 40
h1:
  value: 16
h2:
  value: 64
h3:
  value: 64
learning_rate:
  value: 0.04973663610394374
optimizer:
  value: ada
