wandb_version: 1

batch_size:
  value: 40
criterion:
  value: mse
epochs:
  value: 20
h1:
  value: 256
h2:
  value: 256
h3:
  value: 8
learning_rate:
  value: 0.0030678811448712874
optimizer:
  value: ada
