wandb_version: 1

batch_size:
  value: 103
criterion:
  value: mse
epochs:
  value: 80
h1:
  value: 256
h2:
  value: 8
h3:
  value: 8
learning_rate:
  value: 0.07966101758687001
optimizer:
  value: adam
