wandb_version: 1

batch_size:
  value: 55
criterion:
  value: mse
epochs:
  value: 40
h1:
  value: 256
h2:
  value: 64
h3:
  value: 8
learning_rate:
  value: 0.02367019364769292
optimizer:
  value: adam
