wandb_version: 1

batch_size:
  value: 57
criterion:
  value: mse
epochs:
  value: 100
h1:
  value: 8
h2:
  value: 8
h3:
  value: 64
learning_rate:
  value: 0.05394506810394714
optimizer:
  value: adam
