wandb_version: 1

batch_size:
  value: 35
criterion:
  value: mse
epochs:
  value: 1
h1:
  value: 32
h2:
  value: 8
h3:
  value: 32
learning_rate:
  value: 0.04397408504252496
optimizer:
  value: rms
