wandb_version: 1

batch_size:
  value: 164
criterion:
  value: mse
epochs:
  value: 1
h1:
  value: 32
h2:
  value: 64
h3:
  value: 64
learning_rate:
  value: 0.012730230538359512
optimizer:
  value: rms
