wandb_version: 1

batch_size:
  value: 51
criterion:
  value: mse
epochs:
  value: 1
h1:
  value: 16
h2:
  value: 256
h3:
  value: 16
learning_rate:
  value: 0.06850727245925818
optimizer:
  value: ada
