wandb_version: 1

batch_size:
  value: 136
criterion:
  value: mean_squared_error
epochs:
  value: 80
h1:
  value: 32
h2:
  value: 8
h3:
  value: 64
learning_rate:
  value: 0.018321635906169722
optimizer:
  value: Adagrad
