wandb_version: 1

batch_size:
  value: 242
criterion:
  value: mean_squared_error
epochs:
  value: 40
h1:
  value: 8
h2:
  value: 8
h3:
  value: 32
learning_rate:
  value: 0.09248745042959584
optimizer:
  value: RMSprop
