wandb_version: 1

batch_size:
  value: 133
criterion:
  value: mean_squared_error
epochs:
  value: 40
h1:
  value: 64
h2:
  value: 8
h3:
  value: 8
learning_rate:
  value: 0.06754208799338376
optimizer:
  value: Adam
