wandb_version: 1

batch_size:
  value: 58
criterion:
  value: mean_squared_error
epochs:
  value: 80
h1:
  value: 16
h2:
  value: 256
h3:
  value: 8
learning_rate:
  value: 0.0645836360111409
optimizer:
  value: RMSprop
