wandb_version: 1

batch_size:
  value: 47
criterion:
  value: mean_squared_error
epochs:
  value: 20
h1:
  value: 64
h2:
  value: 32
h3:
  value: 32
learning_rate:
  value: 0.003095771689489224
optimizer:
  value: Adam
