wandb_version: 1

batch_size:
  value: 45
criterion:
  value: mean_squared_error
epochs:
  value: 100
h1:
  value: 32
h2:
  value: 8
h3:
  value: 8
learning_rate:
  value: 0.06670210760430466
optimizer:
  value: Adagrad
