wandb_version: 1

batch_size:
  value: 36
criterion:
  value: mean_squared_error
epochs:
  value: 20
h1:
  value: 32
h2:
  value: 32
h3:
  value: 64
learning_rate:
  value: 0.02066958356275782
optimizer:
  value: RMSprop
