wandb_version: 1

batch_size:
  value: 34
criterion:
  value: mean_squared_error
epochs:
  value: 30
h1:
  value: 8
h2:
  value: 256
h3:
  value: 256
learning_rate:
  value: 0.008501659935149708
optimizer:
  value: Adagrad
