wandb_version: 1

batch_size:
  value: 40
criterion:
  value: mean_squared_error
epochs:
  value: 80
h1:
  value: 8
h2:
  value: 64
h3:
  value: 32
learning_rate:
  value: 0.0020181366243083977
optimizer:
  value: Adagrad
