wandb_version: 1

batch_size:
  value: 43
criterion:
  value: mean_squared_error
epochs:
  value: 20
h1:
  value: 8
h2:
  value: 256
h3:
  value: 16
learning_rate:
  value: 0.04121140016778762
optimizer:
  value: Adam
