wandb_version: 1

batch_size:
  value: 212
criterion:
  value: mean_squared_error
epochs:
  value: 40
h1:
  value: 8
h2:
  value: 32
h3:
  value: 256
learning_rate:
  value: 0.02972711424596305
optimizer:
  value: Adam
