wandb_version: 1

batch_size:
  value: 107
criterion:
  value: mean_squared_error
epochs:
  value: 20
h1:
  value: 16
h2:
  value: 8
h3:
  value: 32
learning_rate:
  value: 0.016224897279560547
optimizer:
  value: Adagrad
