wandb_version: 1

batch_size:
  value: 154
criterion:
  value: mean_squared_error
epochs:
  value: 20
h1:
  value: 32
h2:
  value: 16
h3:
  value: 16
learning_rate:
  value: 0.059468939463682605
optimizer:
  value: Adagrad
