wandb_version: 1

batch_size:
  value: 94
criterion:
  value: mean_squared_error
epochs:
  value: 30
h1:
  value: 8
h2:
  value: 16
h3:
  value: 256
learning_rate:
  value: 0.03168457286476161
optimizer:
  value: RMSprop
