wandb_version: 1

batch_size:
  value: 45
criterion:
  value: mean_squared_error
epochs:
  value: 80
h1:
  value: 32
h2:
  value: 16
h3:
  value: 256
learning_rate:
  value: 0.06003707446556529
optimizer:
  value: RMSprop
