wandb_version: 1

batch_size:
  value: 91
criterion:
  value: mean_squared_error
epochs:
  value: 20
h1:
  value: 16
h2:
  value: 64
h3:
  value: 16
learning_rate:
  value: 0.01023454695901821
optimizer:
  value: RMSprop
