wandb_version: 1

batch_size:
  value: 196
criterion:
  value: mean_squared_error
epochs:
  value: 80
h1:
  value: 64
h2:
  value: 256
h3:
  value: 64
learning_rate:
  value: 0.015487877683376505
optimizer:
  value: Adam
