wandb_version: 1

batch_size:
  value: 179
criterion:
  value: mean_squared_error
epochs:
  value: 80
h1:
  value: 8
h2:
  value: 32
h3:
  value: 256
learning_rate:
  value: 0.07374221218454334
optimizer:
  value: RMSprop
