wandb_version: 1

batch_size:
  value: 206
criterion:
  value: mean_squared_error
epochs:
  value: 20
h1:
  value: 64
h2:
  value: 16
h3:
  value: 256
learning_rate:
  value: 0.022239577925894573
optimizer:
  value: RMSprop
