wandb_version: 1

batch_size:
  value: 42
criterion:
  value: mean_squared_error
epochs:
  value: 100
h1:
  value: 64
h2:
  value: 32
h3:
  value: 8
learning_rate:
  value: 0.026112434000388752
optimizer:
  value: Adam
