wandb_version: 1

batch_size:
  value: 35
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 64
h2:
  value: 256
h3:
  value: 64
learning_rate:
  value: 0.02306248727989334
optimizer:
  value: ada
