wandb_version: 1

batch_size:
  value: 38
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 16
h2:
  value: 16
h3:
  value: 16
learning_rate:
  value: 0.03861901450991763
optimizer:
  value: ada
