wandb_version: 1

batch_size:
  value: 60
criterion:
  value: mean_squared_error
epochs:
  value: 50
h1:
  value: 32
h2:
  value: 64
h3:
  value: 16
learning_rate:
  value: 0.013625029162561197
optimizer:
  value: ada
