wandb_version: 1

batch_size:
  value: 197
criterion:
  value: mean_squared_error
epochs:
  value: 20
h1:
  value: 8
h2:
  value: 64
h3:
  value: 16
learning_rate:
  value: 0.09771581817621652
optimizer:
  value: ada
