wandb_version: 1

batch_size:
  value: 60
criterion:
  value: mean_squared_error
epochs:
  value: 40
h1:
  value: 32
h2:
  value: 8
h3:
  value: 256
learning_rate:
  value: 0.06370818457923996
optimizer:
  value: adam
