wandb_version: 1

batch_size:
  value: 43
criterion:
  value: mean_squared_error
epochs:
  value: 50
h1:
  value: 64
h2:
  value: 256
h3:
  value: 256
learning_rate:
  value: 0.08487398124413416
optimizer:
  value: adam
