wandb_version: 1

batch_size:
  value: 159
criterion:
  value: mse
epochs:
  value: 1
h1:
  value: 16
h2:
  value: 64
h3:
  value: 8
learning_rate:
  value: 0.021595727148173552
optimizer:
  value: sgd
