wandb_version: 1

batch_size:
  value: 232
criterion:
  value: mse
epochs:
  value: 1
h1:
  value: 32
h2:
  value: 256
h3:
  value: 16
learning_rate:
  value: 0.05632085142691513
optimizer:
  value: adam
