wandb_version: 1

batch_size:
  value: 58
criterion:
  value: bce
epochs:
  value: 1
h1:
  value: 8
h2:
  value: 256
h3:
  value: 32
learning_rate:
  value: 0.0354268052251829
optimizer:
  value: sgd
