wandb_version: 1

batch_size:
  value: 40
criterion:
  value: bce
epochs:
  value: 1
h1:
  value: 256
h2:
  value: 64
h3:
  value: 16
learning_rate:
  value: 0.07682665340394766
optimizer:
  value: adam
