wandb_version: 1

batch_size:
  value: 162
criterion:
  value: bce
epochs:
  value: 1
h1:
  value: 256
h2:
  value: 16
h3:
  value: 8
learning_rate:
  value: 0.017674579730614582
optimizer:
  value: sgd
