wandb_version: 1

batch_size:
  value: 74
criterion:
  value: mse
epochs:
  value: 1
h1:
  value: 256
h2:
  value: 8
h3:
  value: 8
learning_rate:
  value: 0.08413400711387355
optimizer:
  value: adam
