wandb_version: 1

batch_size:
  value: 240
criterion:
  value: mse
epochs:
  value: 1
h1:
  value: 16
h2:
  value: 8
h3:
  value: 32
learning_rate:
  value: 0.01168671520838578
optimizer:
  value: adam
