wandb_version: 1

batch_size:
  value: 167
criterion:
  value: bce
epochs:
  value: 1
h1:
  value: 8
h2:
  value: 16
h3:
  value: 8
learning_rate:
  value: 0.029007949157739688
optimizer:
  value: sgd
