wandb_version: 1

batch_size:
  value: 37
criterion:
  value: mse
epochs:
  value: 1
h1:
  value: 16
h2:
  value: 256
h3:
  value: 64
learning_rate:
  value: 0.047318240277978235
optimizer:
  value: sgd
