wandb_version: 1

batch_size:
  value: 181
criterion:
  value: bce
epochs:
  value: 1
h1:
  value: 256
h2:
  value: 64
h3:
  value: 64
learning_rate:
  value: 0.03835827343026818
optimizer:
  value: adam
