wandb_version: 1

batch_size:
  value: 104
criterion:
  value: bce
epochs:
  value: 1
h1:
  value: 256
h2:
  value: 32
h3:
  value: 64
learning_rate:
  value: 0.016783607529003774
optimizer:
  value: adam
