wandb_version: 1

batch_size:
  value: 59
criterion:
  value: mean_squared_error
epochs:
  value: 80
h1:
  value: 8
h2:
  value: 16
h3:
  value: 8
learning_rate:
  value: 0.03419182505965964
optimizer:
  value: rms
