wandb_version: 1

batch_size:
  value: 92
criterion:
  value: mean_squared_error
epochs:
  value: 30
h1:
  value: 32
h2:
  value: 256
h3:
  value: 32
learning_rate:
  value: 0.03872900580054664
optimizer:
  value: ada
