wandb_version: 1

batch_size:
  value: 59
criterion:
  value: mean_squared_error
epochs:
  value: 80
h1:
  value: 32
h2:
  value: 8
h3:
  value: 16
learning_rate:
  value: 0.026485854180956992
optimizer:
  value: rms
