wandb_version: 1

batch_size:
  value: 37
criterion:
  value: mean_squared_error
epochs:
  value: 100
h1:
  value: 16
h2:
  value: 64
h3:
  value: 16
learning_rate:
  value: 0.022681930781855954
optimizer:
  value: ada
