wandb_version: 1

batch_size:
  value: 154
criterion:
  value: mean_squared_error
epochs:
  value: 20
h1:
  value: 32
h2:
  value: 32
h3:
  value: 16
learning_rate:
  value: 0.07454029157402584
optimizer:
  value: ada
