wandb_version: 1

batch_size:
  value: 169
criterion:
  value: mean_squared_error
epochs:
  value: 30
h1:
  value: 64
h2:
  value: 16
h3:
  value: 16
learning_rate:
  value: 0.05169772613093179
optimizer:
  value: rms
