wandb_version: 1

batch_size:
  value: 73
criterion:
  value: mean_squared_error
epochs:
  value: 20
h1:
  value: 8
h2:
  value: 64
h3:
  value: 32
learning_rate:
  value: 0.06672573811613619
optimizer:
  value: rms
