wandb_version: 1

batch_size:
  value: 34
criterion:
  value: mean_squared_error
epochs:
  value: 100
h1:
  value: 8
h2:
  value: 16
h3:
  value: 32
learning_rate:
  value: 0.0791429372975026
optimizer:
  value: ada
