wandb_version: 1

batch_size:
  value: 43
criterion:
  value: mean_squared_error
epochs:
  value: 100
h1:
  value: 8
h2:
  value: 32
h3:
  value: 32
learning_rate:
  value: 0.07192545647338736
optimizer:
  value: ada
