wandb_version: 1

batch_size:
  value: 58
criterion:
  value: mean_squared_error
epochs:
  value: 20
h1:
  value: 8
h2:
  value: 32
h3:
  value: 256
learning_rate:
  value: 0.009799686935354225
optimizer:
  value: ada
