wandb_version: 1

batch_size:
  value: 73
criterion:
  value: mean_squared_error
epochs:
  value: 20
h1:
  value: 256
h2:
  value: 8
h3:
  value: 256
learning_rate:
  value: 0.08756562052656118
optimizer:
  value: ada
