wandb_version: 1

batch_size:
  value: 133
criterion:
  value: mean_squared_error
epochs:
  value: 30
h1:
  value: 256
h2:
  value: 64
h3:
  value: 32
learning_rate:
  value: 0.09588524740080642
optimizer:
  value: rms
