wandb_version: 1

batch_size:
  value: 36
criterion:
  value: mean_squared_error
epochs:
  value: 30
h1:
  value: 64
h2:
  value: 16
h3:
  value: 64
learning_rate:
  value: 0.08996160920790638
optimizer:
  value: adam
