wandb_version: 1

batch_size:
  value: 51
criterion:
  value: mean_squared_error
epochs:
  value: 80
h1:
  value: 16
h2:
  value: 8
h3:
  value: 64
learning_rate:
  value: 0.01144039004686841
optimizer:
  value: adam
