wandb_version: 1

batch_size:
  value: 126
criterion:
  value: mean_squared_error
epochs:
  value: 50
h1:
  value: 16
h2:
  value: 64
h3:
  value: 64
learning_rate:
  value: 0.03263208070213258
optimizer:
  value: ada
