wandb_version: 1

batch_size:
  value: 95
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 32
h2:
  value: 8
h3:
  value: 256
learning_rate:
  value: 0.094794602454492
optimizer:
  value: sgd
