wandb_version: 1

batch_size:
  value: 47
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 8
h2:
  value: 16
h3:
  value: 64
learning_rate:
  value: 0.03012588258306144
optimizer:
  value: sgd
