wandb_version: 1

batch_size:
  value: 86
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 32
h2:
  value: 8
h3:
  value: 32
learning_rate:
  value: 0.08558086872807523
optimizer:
  value: adam
