wandb_version: 1

batch_size:
  value: 74
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 256
h2:
  value: 16
h3:
  value: 64
learning_rate:
  value: 0.016256546464224555
optimizer:
  value: adam
