wandb_version: 1

batch_size:
  value: 202
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 8
h2:
  value: 64
h3:
  value: 32
learning_rate:
  value: 0.061706673231097534
optimizer:
  value: adam
