wandb_version: 1

batch_size:
  value: 149
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 16
h2:
  value: 64
h3:
  value: 16
learning_rate:
  value: 0.05248918014541592
optimizer:
  value: adam
