wandb_version: 1

batch_size:
  value: 75
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 16
h2:
  value: 64
h3:
  value: 256
learning_rate:
  value: 0.05229020329567035
optimizer:
  value: sgd
