wandb_version: 1

batch_size:
  value: 54
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 16
h2:
  value: 16
h3:
  value: 16
learning_rate:
  value: 0.012560710684450027
optimizer:
  value: sgd
