wandb_version: 1

batch_size:
  value: 41
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 64
h2:
  value: 256
h3:
  value: 8
learning_rate:
  value: 0.039749957137048646
optimizer:
  value: sgd
