wandb_version: 1

batch_size:
  value: 79
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 16
h2:
  value: 256
h3:
  value: 8
learning_rate:
  value: 0.031109396497481057
optimizer:
  value: sgd
