wandb_version: 1

batch_size:
  value: 100
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 8
h2:
  value: 32
h3:
  value: 16
learning_rate:
  value: 0.016710817904750465
optimizer:
  value: adam
