wandb_version: 1

batch_size:
  value: 69
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 16
h2:
  value: 16
h3:
  value: 8
learning_rate:
  value: 0.06744209516151949
optimizer:
  value: adam
