wandb_version: 1

batch_size:
  value: 147
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 32
h2:
  value: 16
h3:
  value: 8
learning_rate:
  value: 0.041021958564522704
optimizer:
  value: ada
