wandb_version: 1

batch_size:
  value: 133
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 256
h2:
  value: 256
h3:
  value: 64
learning_rate:
  value: 0.016898226648887106
optimizer:
  value: ada
