wandb_version: 1

batch_size:
  value: 33
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 256
h2:
  value: 16
h3:
  value: 16
learning_rate:
  value: 0.07707822513919899
optimizer:
  value: rms
