wandb_version: 1

batch_size:
  value: 94
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 64
h2:
  value: 16
h3:
  value: 32
learning_rate:
  value: 0.05375591597384677
optimizer:
  value: rms
