wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 1
      - 3
      - 5
      4: 3.8.3
      5: 0.10.22
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 232
criterion:
  desc: null
  value: mse
epochs:
  desc: null
  value: 1
h1:
  desc: null
  value: 32
h2:
  desc: null
  value: 256
h3:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.05632085142691513
optimizer:
  desc: null
  value: adam
