wandb_version: 1

batch_size:
  value: 42
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 8
h2:
  value: 8
h3:
  value: 256
learning_rate:
  value: 0.020881367106537752
optimizer:
  value: ada
