wandb_version: 1

batch_size:
  value: 68
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 8
h2:
  value: 64
h3:
  value: 64
learning_rate:
  value: 0.09509111671955489
optimizer:
  value: adam
