wandb_version: 1

batch_size:
  value: 197
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 8
h2:
  value: 256
h3:
  value: 8
learning_rate:
  value: 0.058971445537667866
optimizer:
  value: ada
