wandb_version: 1

batch_size:
  value: 67
criterion:
  value: mse
epochs:
  value: 50
h1:
  value: 8
h2:
  value: 8
h3:
  value: 64
learning_rate:
  value: 0.05516327809927233
optimizer:
  value: ada
